export const INBOX_CATEGORY_IDS = [
  "bills",
  "school",
  "travel",
  "appointments",
  "subscriptions",
  "home",
  "receipts",
  "bank",
  "security",
  "needs_review",
] as const;

export type InboxCategory = (typeof INBOX_CATEGORY_IDS)[number];

export const GMAIL_USEFUL_CATEGORY_IDS = [
  "bills",
  "school",
  "travel",
  "appointments",
  "subscriptions",
  "home",
  "receipts",
  "bank",
  "security",
] as const;

export type GmailUsefulCategory = (typeof GMAIL_USEFUL_CATEGORY_IDS)[number];

export const INBOX_SUBCATEGORY_IDS = [
  "utility_bill",
  "credit_card_bill",
  "loan_payment",
  "insurance_premium",
  "tax_payment",
  "rent",
  "medical_bill",
  "school_fee",
  "purchase_receipt",
  "food_delivery",
  "refund",
  "warranty",
  "bank_transaction",
  "bank_statement",
  "credit_card_statement",
  "investment",
  "demat",
  "otp",
  "login_code",
  "sign_in_alert",
  "password_reset",
  "field_trip",
  "school_event",
  "permission_form",
  "report_card",
  "timetable",
  "school_transport",
  "flight",
  "train",
  "bus",
  "hotel",
  "visa",
  "itinerary",
  "booking_change",
  "medical_appointment",
  "service_appointment",
  "government_appointment",
  "reservation",
  "subscription_renewal",
  "subscription_price_change",
  "trial_ending",
  "subscription_cancellation",
  "home_maintenance",
  "delivery",
  "community_notice",
  "household_service",
  "other",
] as const;

export type InboxSubcategory = (typeof INBOX_SUBCATEGORY_IDS)[number];
